#!/usr/bin/env bash

IMAGE="bdclark/ecr-credential-helper:latest"

# pass AWS access vars to container if they are set
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  ENV_ARGS="${ENV_ARGS} -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
fi

# pass AWS region var to container if set,
# otherwise attempt to set region from EC2 metadata
if [ -n "$AWS_REGION" ]; then
  ENV_ARGS="${ENV_ARGS} -e AWS_REGION=$AWS_REGION"
else
  az=$(curl --fail -m 2 -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
  if [ $? -eq 0 ] && [ -n "$az" ];then
    ENV_ARGS="${ENV_ARGS} -e AWS_REGION=${az:0:-1}"
  fi
fi

cat - | exec docker run --rm -i $ENV_ARGS $IMAGE "$@"
